### ISSUE TITLE
Terminal error during local runtime upon btn "get certificate"

### ISSUE THREAD

**Issue by IyaadArshad** [ShivamJoker/Cert-Generator#5]
Issue occurs when running locally
Terminal msg:
Could not read source map for https://unpkg.com/pdf-lib@1.4.0: Unexpected 404 response from https://unpkg.com/pdf-lib.min.js.map: Cannot find package pdf-lib.min.js.map@latest
Uncaught TypeError TypeError: Failed to fetch
    at generatePDF (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:25:34)
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)
    --- await ---
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)
Uncaught TypeError TypeError: Failed to fetch
    at generatePDF (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:25:34)
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)
    --- await ---
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)
Uncaught TypeError TypeError: Failed to fetch
    at generatePDF (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:25:34)
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)
    --- await ---
    at <anonymous> (c:\Users\Iyaad\OneDrive\Desktop\Downloads\Cert-Generator-master\index.js:18:5)

**Comment by ShivamJoker** [comment]
Please provide reproduction details.

**Comment by IyaadArshad** [comment]
I can't describe it very effectively but I can give a brief overview.
Running a standard chrome edition
Downloaded source code and attempted to run code on chrome. **Failed**
Attempted to run on localhost and the same issue came
Went into developer tools console and the log is above

**Comment by ShivamJoker** [comment]
this link is working https://unpkg.com/pdf-lib@1.4.0
you might be having some firewall try using it via npm and the import syntax

**Comment by IyaadArshad** [comment]
Yea so the problem is the code doesn't work locally, but when its hosted on a server it works fine

**Comment by ShivamJoker** [comment]
It seems like your firewall issue.
It's not related to the project, for further help you can contact me for paid support.

**Comment by IyaadArshad** [comment]
its a local issue with fetching **index.js** due to some issue. Other people also have this issue

**Comment by IyaadArshad** [comment]
### Downloads issue #4
Same issue

**Comment by ShivamJoker** [comment]
Please use local server to view the site, don't open index.html directly.
